[package]
name = "harness_client"
version = "0.1.0"
authors = ["Marta Mularczyk <mulmarta@amazon.ch>"]
edition = "2021"
publish = false

[dependencies]
mls-rs = { version = "0.42.0", path = "..", default-features = false, features = ["std", "external_client"]}
tonic = "0.10.2"
prost = "0.12.1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
clap = { version = "4", features = ["derive"] }
thiserror = "1"
hex = "0.4"

[features]
tree_index = [ "mls-rs/tree_index" ]
private_message = [ "mls-rs/private_message" ]
prior_epoch = [ "mls-rs/prior_epoch" ]
out_of_order = [ "mls-rs/out_of_order", "private_message" ]
psk = [ "mls-rs/psk" ]
custom_proposal = [ "mls-rs/custom_proposal" ]
by_ref_proposal = [ "mls-rs/by_ref_proposal" ]
default = ["tree_index", "private_message", "prior_epoch", "out_of_order", "psk", "custom_proposal", "by_ref_proposal"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
mls-rs-crypto-rustcrypto = { path = "../../mls-rs-crypto-rustcrypto", features = ["browser"], version = "0.11.0" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
mls-rs-crypto-openssl = { path = "../../mls-rs-crypto-openssl", version = "0.10.0"}

[build-dependencies]
tonic-build = "0.10.2"
