name: Fuzz Tests
on: [pull_request]
env:
  CARGO_TERM_COLOR: always
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
  RUNS: 10000
  TIME: 300
jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: dtolnay/rust-toolchain@nightly
        - name: Install cargo-fuzz
          run: cargo install cargo-fuzz
        - name: Run Fuzz Targets
          working-directory: mls-rs
          run: |
            cargo +nightly fuzz run application_data -- -runs=$RUNS -timeout=$TIME
            cargo +nightly fuzz run cipher_text -- -runs=$RUNS -timeout=$TIME
            cargo +nightly fuzz run deserialize -- -runs=$RUNS -timeout=$TIME
            cargo +nightly fuzz run export_secret -- -runs=$RUNS -timeout=$TIME
            cargo +nightly fuzz run mls_message -- -runs=$RUNS -timeout=$TIME
            cargo +nightly fuzz run process_bytes -- -runs=$RUNS -timeout=$TIME
