name: WASM
on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
  WASM_BINDGEN_TEST_TIMEOUT: 1000
  RUSTFLAGS: "--cfg mls_build_async"
jobs:
  BuildAndTest:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - uses: nanasess/setup-chromedriver@v2
    - uses: jetli/wasm-pack-action@v0.3.0
      with:
        version: 'v0.10.3'
    - name: WASM mls-rs-crypto-rustcrypto
      working-directory: mls-rs-crypto-rustcrypto
      run: wasm-pack test --headless --chrome --release --features browser
    - name: WASM mls-rs
      working-directory: mls-rs
      run: wasm-pack test --headless --chrome --release --lib --test '*' --features test_util
    - name: WASM mls-rs-identity-x509
      working-directory: mls-rs-identity-x509
      run: wasm-pack test --headless --chrome --release
    - name: WASM mls-rs-crypto-webcrypto
      working-directory: mls-rs-crypto-webcrypto
      run: wasm-pack test --headless --chrome --release

